### ISSUE TITLE
/mattermost/data empty after new install

### ISSUE THREAD

**Issue by oal22** [mattermost/mattermost-helm#200] opened 2020-11-26 11:34 UTC
Hi,
i install Chart with Persistent Volume on Azure AKS.
I log in the Container and create some Directories: mkdir /mattermost/data/pics
but after new install die Directory is gone

$ ls -al /mattermost/data/
total 32
drwxrwsr-x    4 root     mattermo      4096 Nov 25 13:29 .
drwxr-sr-x    1 mattermo mattermo      4096 Nov 25 13:35 ..
drwxrws---    2 root     mattermo     16384 Nov 25 13:28 lost+found
drwxr-s---    3 mattermo mattermo      4096 Nov 25 13:29 users

How is that possible ?

      volumeMounts:
        - mountPath: /mattermost/config/config.json
          name: config-json
          subPath: config.json
        - mountPath: /mattermost/data
          name: mattermost-data
        - mountPath: /mattermost/plugins
          name: mattermost-plugins
        resources:
            null
      volumes:
      - name: config-json
        secret:
          secretName: mm-mattermost-team-edition-config-json
      - name: mattermost-data

        persistentVolumeClaim:
          claimName: mm-mattermost-team-edition

      - name: mattermost-plugins

        persistentVolumeClaim:

          claimName: mm-mattermost-team-edition-plugins

**Comment by cpanato** [comment] 2021-06-14 15:24
I deployed that in AWS and in my local machine using kind and I was not able to reproduce this issue

make sure you are not deleting your PV/PVC, otherwise, the data will be lost


will close this issue, if you need are still facing this issue, feel free to reopen and add more information

**Closed by cpanato** 2021-06-14 15:24 UTC
