### ISSUE TITLE
Cant start pod. 

### ISSUE THREAD

**Issue by Tony-The-Developer** [mattermost/mattermost-helm#215] opened 2021-03-26 20:32 UTC
Using NFS for file storage. Used to work now not working. What user and group does the nfs share need to be set to. 

Error: failed to load configuration: failed to create store: unable to load on store creation: failed to persist: failed to write file: open /mattermost/config/config.json: permission denied

**Comment by cpanato** [comment] 2021-04-06 10:26
duplicate of https://github.com/mattermost/mattermost-helm/issues/203

**Closed by cpanato** 2021-04-06 10:26 UTC
